apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: text-generation-webui-timeout-config
spec:
  timeoutSec: 1200
---
apiVersion: v1
kind: Service
metadata:
  name: text-generation-webui
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "text-generation-webui-timeout-config"}'
spec:
  ports:
  - name: webui
    protocol: TCP
    port: 80
    targetPort: 7860
  - name: api
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: streaming
    protocol: TCP
    port: 5005
    targetPort: 5005
  selector:
    app: text-generation-webui
