# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

labels:
- includeSelectors: true
  pairs:
    env: dev

patches:
  - path: patch-deployment.yaml