# patch-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-generation-webui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-generation-webui
  strategy:
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
